### ISSUE TITLE
Develop the sub Modules needed for data pipeline

### ISSUE THREAD

**Issue by AdityaNPL** [mgalas/Landscape4Data#13]
Start to develop the sub-modules like auditing and generating metadata. Also, Design a software architecture to integrate everything.

**Comment by AdityaNPL** [comment]
Developed the Retrieve, CleanOrganise and the main classes. Need some more information for Audit and MetaData. Developing Scheduler.

**Comment by chengmar09** [comment]
Questions have been answered, modules developed
